version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
